# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9972e04450b61392377818b559b76ccc68ffa14415d809bb663330ffa9ae2cee3abe4f976d126f93f85a2756256fa924c07553456e36c2059d071214b4b2715b

test:
  secret_key_base: b7e76de6b77f4f88665fd245d434bd47677f6f1f8b9607fcfed295f843d0c73caff3526d454cc6372d88b1ee5a34e0b1120ef28b8939f691e6c5a50d8e81140a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
